test conditions

diff --git a/.github/workflows/matrix.yml b/.github/workflows/matrix.yml
--- a/.github/workflows/matrix.yml
+++ b/.github/workflows/matrix.yml
@@ -13,18 +13,18 @@ jobs:
     outputs:
       matrix: ${{ steps.evaluate.outputs.matrix }}
     steps:
-    - name: Create matrix
-      id: evaluate
-      run: |
+      - name: Create matrix
+        id: evaluate
+        run: |
           MATRIX='[{name: "matrix 1", id: "1"},{name: "matrix 2", id: "2"},{name: "matrix 3", id: "3"}]'
           echo "$MATRIX"
           echo "matrix=$MATRIX" >> "$GITHUB_OUTPUT"
-#          echo "matrix='[]'" >> "$GITHUB_OUTPUT"
+          #          echo "matrix='[]'" >> "$GITHUB_OUTPUT"
           echo ${{ github.event_name }}
   matrix-job:
     name: "Run ${{ matrix.name }}"
     runs-on: ubuntu-latest
-    needs: [create-matrix]
+    needs: [ create-matrix ]
     outputs:
       evaluation: ${{ steps.evaluate.run.evaluation }}
     strategy:
@@ -33,63 +33,63 @@ jobs:
         include: ${{fromJson( needs.create-matrix.outputs.matrix )}}
 
     steps:
-    - uses: actions/checkout@v4
+      - uses: actions/checkout@v4
 
-    - name: Set env value
-      run: |
-        echo "Name: ${{matrix.name}}"
-        echo "Id: ${{matrix.id}}"
-        if [ ${{ matrix.id }} == 1 ]; then echo "MATRIX_1=true" >> $GITHUB_ENV; fi
-#        if [[ ${{ matrix.name }} == *matrix ]]; then echo "matrix tests"; fi
+      - name: Set env value
+        run: |
+          echo "Name: ${{matrix.name}}"
+          echo "Id: ${{matrix.id}}"
+          if [ ${{ matrix.id }} == 1 ]; then echo "MATRIX_1=true" >> $GITHUB_ENV; fi
+      #        if [[ ${{ matrix.name }} == *matrix ]]; then echo "matrix tests"; fi
 
-    - name: Run ${{ matrix.name }} tests
-      id: run
-      env:
-        RUN_ID: ${{ matrix.id }}
-      run: |
-        sleep ${{ matrix.id }}
-
-        echo ${{strategy.job-index}}
-
-        echo "$MATRIX_1"
-        echo ${{ env.MATRIX_1 }}
-        echo $RUN_ID >> metadata.json
-        cat metadata.json
-        
-        # fail fail fail
-        if [ ${{ matrix.id }} == 2 ]; then exit 1; fi
-
-        # Write output
-        echo "evaluation={\"key\":\"value\"}" >> "$GITHUB_OUTPUT"
+      - name: Run ${{ matrix.name }} tests
+        id: run
+        env:
+          RUN_ID: ${{ matrix.id }}
+        run: |
+          sleep ${{ matrix.id }}
+          
+          echo ${{strategy.job-index}}
+          
+          echo "$MATRIX_1"
+          echo ${{ env.MATRIX_1 }}
+          echo $RUN_ID >> metadata.json
+          cat metadata.json
+          
+          # fail fail fail
+          if [ ${{ matrix.id }} == 2 ]; then exit 1; fi
+          
+          # Write output
+          echo "evaluation={\"key\":\"value\"}" >> "$GITHUB_OUTPUT"
 
   conditional-job:
     name: "Report"
     runs-on: ubuntu-latest
     if: ${{ github.event_name != 'pull_request' }}
-    needs: [matrix-job]
+    needs: [ matrix-job ]
 
     steps:
-    - uses: actions/checkout@v4
+      - uses: actions/checkout@v4
 
-    - name: Notify
-      run: |
-        echo ${{ needs.matrix-job.result }}
+      - name: Notify
+        run: |
+          echo ${{ needs.matrix-job.result }}
   
   evaluate-job:
     name: "Evaluate"
     runs-on: ubuntu-latest
     if: ${{ always() }}
-    needs: [matrix-job]
+    needs: [ matrix-job ]
     env:
       NEEDS_CTX: ${{ fromJSON(needs.matrix-job.outputs) }}
 
     steps:
-    - name: Evaluate
-      run: |
-        result="${{ needs.*.result }}"
-        echo $result
-        echo $NEEDS_CTX
-        if [[ $result != "success" && $result != "skipped" ]]; then
-          echo "One or more needed jobs have failed."
-          exit 1
-        fi
+      - name: Evaluate
+        run: |
+          result="${{ needs.*.result }}"
+          echo $result
+          echo $NEEDS_CTX
+          if [[ $result != "success" && $result != "skipped" ]]; then
+            echo "One or more needed jobs have failed."
+            exit 1
+          fi
